In [1]:
import os, sys, importlib
import pandas as pd
sys.path.append(os.path.abspath(".."))
from utils import preprocess_listings

In [3]:
path_listings_grouped="data_jo_2_grouped1\listings_jo_paris2406_grouped.csv"
df_raw=pd.read_csv(path_listings_grouped)
df=df_raw.copy()
print(len(df))
print(df.columns)
display(df.head())

C:\Users\yeliu\AppData\Local\Temp\ipykernel_19708\1469547325.py:2: DtypeWarning: Columns (77,79) have mixed types. Specify dtype option on import or set low_memory=False.
  df_raw=pd.read_csv(path_listings_grouped)

95885
Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name',
       'description', 'neighborhood_overview', 'picture_url', 'host_id',
       'host_url', 'host_name', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'first_review',
       'last_review', 'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month',
       'scraped_date', 'status', 'host_about_q1', 'host_about_changed',
       'host_picture_url_q1', 'host_picture_url_changed',
       'presentation_change', 'is_changed'],
      dtype='object')

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,calculated_host_listings_count_shared_rooms,reviews_per_month,scraped_date,status,host_about_q1,host_about_changed,host_picture_url_q1,host_picture_url_changed,presentation_change,is_changed
0,80260,https://www.airbnb.com/rooms/80260,20240610195007,2024-06-13,previous scrape,Nice studio in Jourdain's village,NaN,NaN,https://a0.muscache.com/pictures/716553/6c14f2...,333548,...,0,1.29,2024Q2,old_host,"My name is Charlotte, I'm 26 and I study cinem...",0,https://a0.muscache.com/im/users/333548/profil...,0,0,False
1,3109,https://www.airbnb.com/rooms/3109,20240610195007,2024-06-12,city scrape,zen and calm,Lovely Appartment with one bedroom with a Quee...,Good restaurants<br />very close the Montparna...,https://a0.muscache.com/pictures/miso/Hosting-...,3631,...,0,0.05,2024Q2,old_host,NaN,0,https://a0.muscache.com/im/users/3631/profile_...,0,0,False
2,80301,https://www.airbnb.com/rooms/80301,20240610195007,2024-06-13,city scrape,toits de Paris,"On the top,sharing my space,you have your bedr...","SAFE neighborhood,late bus and subway,velibe(b...",https://a0.muscache.com/pictures/742354/2e66b9...,433758,...,0,0.27,2024Q2,old_host,"Doctorat Sorbonne 1,Litterature sciences huma...",0,https://a0.muscache.com/im/users/433758/profil...,0,0,False
3,5396,https://www.airbnb.com/rooms/5396,20240610195007,2024-06-13,city scrape,Your perfect Paris studio on Île Saint-Louis,"NEW SOFA-BED SINCE JUNE 2023, Please disregard...","You are within walking distance to the Louvre,...",https://a0.muscache.com/pictures/52413/f9bf76f...,7903,...,0,2.21,2024Q2,old_host,We have spent a lot of time traveling for work...,0,https://a0.muscache.com/im/users/7903/profile_...,0,0,False
4,7397,https://www.airbnb.com/rooms/7397,20240610195007,2024-06-13,city scrape,MARAIS - 2ROOMS APT - 2/4 PEOPLE,"VERY CONVENIENT, WITH THE BEST LOCATION !",NaN,https://a0.muscache.com/pictures/67928287/330b...,2626,...,0,2.21,2024Q2,old_host,"I am a writer,54, author of novels, books of l...",0,https://a0.muscache.com/im/pictures/user/ad6a9...,0,0,False

## host_vars=> df_processed

In [4]:
importlib.reload(preprocess_listings)
from utils.preprocess_listings import preprocess_host_variables, print_nan_ratio
df_processed=preprocess_host_variables(df)

******************************HOST VARS******************************
PROCESS PIPELINE :
- host_is_sueprhost: fillna('f')
- review_scores_rating: 34.0% NaN; fillna(0), to numeric; ADD 'has_rating' :1/0'
- host_since: ADD 'years_since_host' :float, 0.5-1 year=>1， 0-0.5 year => 0
- has_host_about: ADD 'has_host_about':1/0','lang:en/fr/other_langs','len:int',
- host_response_time:40.0% NaN, fillna('no_response_time')
- host_response_rate:40.0% NaN, ADD 'has_response_rate' :1/0， fillna(0)
- calculated_host_listings_count : ADD 'professional_host:1/0'

==========================HOST VARS================================
17 IMPO VARS:['host_picture_url', 'host_identity_verified', 'number_of_reviews', 'host_is_superhost', 'review_scores_rating', 'has_rating', 'host_since', 'years_since_host', 'host_about', 'has_host_about', 'lang', 'len', 'host_response_time', 'host_response_rate', 'has_response_rate', 'calculated_host_listings_count', 'professional_host']

================= BALN PROCESSED VARIABLES =====================
[WARINNG] NaN in host_picture_url!!
host_picture_url
https://a0.muscache.com/defaults/user_pic-225x225.png?v=3                                                                                3727
https://a0.muscache.com/im/pictures/user/0afb4368-deff-4ea7-b48e-d1ef5a40ea9a.jpg?aki_policy=profile_x_medium                             730
https://a0.muscache.com/im/pictures/user/cefcf382-a8fe-4348-9bba-ae00462784ca.jpg?aki_policy=profile_x_medium                             497
https://a0.muscache.com/im/pictures/user/f1221c8c-c1be-4947-aaa7-4fca4221b75c.jpg?aki_policy=profile_x_medium                             426
https://a0.muscache.com/im/pictures/user/User-50978178/original/f8b585d7-a644-46a3-bb64-7dc6ef49fde2.jpeg?aki_policy=profile_x_medium     307
                                                                                                                                         ...
https://a0.muscache.com/im/users/108444/profile_pic/1310919783/original.jpg?aki_policy=profile_x_medium                                     1
https://a0.muscache.com/im/pictures/user/User-532468/original/b7887167-60ae-4048-9bfc-3bac666ec234.jpeg?aki_policy=profile_x_medium         1
https://a0.muscache.com/im/pictures/user/User-107514/original/211929e2-643f-452f-ae1a-64511f78c0b6.jpeg?aki_policy=profile_x_medium         1
https://a0.muscache.com/im/users/546512/profile_pic/1304181922/original.jpg?aki_policy=profile_x_medium                                     1
https://a0.muscache.com/im/pictures/user/bd80fced-7c1e-4b41-9aec-0ef83f1ee107.jpg?aki_policy=profile_x_medium                               1
Name: count, Length: 68562, dtype: int64

-----------------------------------------------------------
[WARINNG] NaN in host_identity_verified!!
host_identity_verified
t      86326
f       9551
NaN        8
Name: count, dtype: int64

-----------------------------------------------------------
- number_of_reviews: 0% NaN !
- number_of_reviews: 34.0% 0 !

count    95885.000000
mean        19.888189
std         52.040205
min          0.000000
25%          0.000000
50%          3.000000
75%         18.000000
max       3067.000000
Name: number_of_reviews, dtype: float64

-----------------------------------------------------------
no NaN in host_is_superhost:)
host_is_superhost
f    81109
t    14776
Name: count, dtype: int64

-----------------------------------------------------------
- review_scores_rating: 0% NaN !
- review_scores_rating: 34.0% 0 !

count    95885.000000
mean         3.138655
std          2.253393
min          0.000000
25%          0.000000
50%          4.600000
75%          4.920000
max          5.000000
Name: review_scores_rating, dtype: float64

-----------------------------------------------------------
no NaN in has_rating:)
has_rating
1    63697
0    32188
Name: count, dtype: int64

-----------------------------------------------------------
- host_since: 0.0% NaN !
- host_since: 0.0% 0 !

count                            95877
mean     2017-05-21 19:04:17.166995200
min                2008-08-30 00:00:00
25%                2014-08-06 00:00:00
50%                2016-05-01 00:00:00
75%                2019-12-08 00:00:00
max                2024-06-09 00:00:00
Name: host_since, dtype: object

-----------------------------------------------------------
- years_since_host: 0% NaN !
- years_since_host: 5.0% 0 !

count    95885.000000
mean         7.055994
std          3.635189
min          0.000000
25%          5.000000
50%          8.000000
75%         10.000000
max         16.000000
Name: years_since_host, dtype: float64

-----------------------------------------------------------
[WARINNG] NaN in host_about!!
host_about
NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                54827
We’re Blueground, a global proptech company with several thousand move-in-ready apartments in a growing number of major cities around the world. With flexible terms and homes in vibrant, centrally based neighborhoods, you’ll feel at home and free to roam for as long as you want — a month, a year, or longer. \n\nEach apartment is thoughtfully designed with exclusive furnishings, fully equipped kitchens, and incredible amenities – making every day a five-star experience. From day one, you’ll enjoy high-speed Wi-Fi, premium linens, and smart home entertainment. Plus, access to pools, gyms, and outdoor spaces in select buildings.\n\nWhy stress over your apartment? We provide a hassle-free alternative — a consistent, quality guest experience that starts even before you arrive. Because we let you book our most up-to-date apartment listings online, confirm with a click, pay securely, and check in easily. \n\nDuring your stay\nUpon arrival, you’ll either be greeted personally by a Blueground team member or given self-check-in instructions. The entire apartment is yours! You’ll enjoy reliable support via email, phone, and our Guest App, where you can request everything from a home cleaning to extra towels. \n\nWe’ll share all details upon confirmation of your stay.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         730
Greetings from the Veeve team!\n\n\nVeeve manage the largest collection of homes to rent for short stays in London since 2011, launching in Paris in 2017. Our rental homes are predominantly privately-owned, lived-in homes in vibrant neighbourhoods. Thanks to our fully managed service, when you stay in a Veeve property you can benefit from the spaciousness, personal style and relaxed feel of a home – but with all the amenities of a hotel.\n\n\nOnce a booking is confirmed our Customer Service team will become your main point of contact and get in touch with you to organise your arrival at the property (including airport transfers, upon request); after which our on-the-ground management team will look after all aspects of your stay, with in-stay support available to help with any queries.\n\n\nWe have strict cleanliness guidelines for our cleaners and all staff who enter our properties and have reinforced existing cleaning procedures in line with official WHO, British and French government guidance.\n\n\nAs always, our team ensure that all properties are cleaned to a professional standard before and after each stay, with increased focus on touch-point cleaning (door handles, kitchen surfaces, kettles, taps etc.).\n\n All staff who enter properties will follow the below procedures:\n \n\n- Carry and regularly use alcohol-based hand rub\n- Sanitise their mobile phones \n- Focus extra attention when cleaning key touch-point areas (door handles, kitchen surfaces, kettles, taps etc.)\n- Wear protective gear where appropriate\n- Wash and disinfect work shoes\n\n\nWe might be able to arrange for property viewings, upon request, for stays of over 28 nights. \n\nPlease be aware once a booking is confirmed you will be required to complete a Rental Agreement and also  ID verification via our partners Superhog. This is mandatory for all our stays and in accordance to short lets requirements with Veeve.\n\nIf you have any questions, please do not hesitate to contact us and we will be sure to answer you promptly.      497
Bonjour, \nExperts Airbnb depuis 10 ans, nous serons ravis de vous apporter notre aide de la création de votre annonce jusqu'à la gestion de votre logement.\n\nNous sommes disponibles de 10:00 à 18:00                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             426
At GuestReady, we're on a mission to redefine modern hospitality. We specialise in helping hosts deliver outstanding experiences to their guests worldwide. With years of hospitality experience, we're dedicated to providing an exceptional experience. Let us help you find the perfect place for an unforgettable stay!                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          332
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ...
Bonjour, je démarre la location de mon logement pendant mes périodes d’absence. \nParisien depuis 2011. \nJ’aurai plaisir à vous accueillir chez moi ainsi qu'à vous partager mes recommandations suivant vos envies !                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 1

## proxy, obj_vars, location => df_filtered

In [8]:
importlib.reload(preprocess_listings)
from utils.preprocess_listings import preprocess_obj_vars
df_filtered=preprocess_obj_vars(df=df_processed, 
                        proxy_vars=['price',"availability_30","availability_90"], 
                        get_boooking_rate_l30d=False, filtrate_by_booking_rate=False, 
                        obj_vars=["room_type", "minimum_nights","instant_bookable"], 
                        threshold_km=3, 
                        output_folder="data_jo_3_filtered", filename=None)

**********************************PROXY + OBJ VARS**********************************
PROCESS PIPELINE :
1) process proxies :
 clean + dropna  : price, availability_30, availability_90
 ==> get df_filtered

 2) if get_boooking_rate_l30d==True, calculation method:
- booking_rate_l30d = number_of_reviews_l30d / availability_30
 note that many 'number_of_reviews_l30d' is 0!
 if availability_30 = 0, take NaN.
 if booking_rate_l30d > 1, take 1.

3) desc statistique :room_type, minimum_nights, instant_bookable

4) if enter 'threshold_km':
location :'latitude','longitude': ADD 'is_within_Xkm'
calculate  distance bewtween listing and its cloest venue. if it's under 3 km, 'is_within_3 km' ==1, else 0.



==============================PROXY=============================

- price: 22.0% NaN'

[INFO]21306 nan dropped in price
[INFO]0 nan dropped in availability_30
[INFO]0 nan dropped in availability_90

len BEFORE filtrage by price; availability_30; availability_90: 95885
len AFTER: 74579



 ==============================LOCATION=============================

is_within_3km
1    64912
0     9667
Name: count, dtype: int64
================= BALN PROCESSED VARIABLES =====================
[INFO] statictic description on df (74579 lines):
price ; availability_30 ; availability_90 ; room_type ; minimum_nights ; instant_bookable ; is_within_3km

- price: 0% NaN !
- price: 0.0% 0 !

count    74579.000000
mean       289.075155
std        684.010923
min         10.000000
25%        109.000000
50%        164.000000
75%        290.000000
max      72000.000000
Name: price, dtype: float64

-----------------------------------------------------------
- availability_30: 0% NaN !
- availability_30: 28.000000000000004% 0 !

count    74579.000000
mean        10.620778
std         10.391219
min          0.000000
25%          0.000000
50%          8.000000
75%         19.000000
max         30.000000
Name: availability_30, dtype: float64

-----------------------------------------------------------
- availability_90: 0% NaN !
- availability_90: 4.0% 0 !

count    74579.000000
mean        48.044704
std         26.358149
min          0.000000
25%         27.000000
50%         48.000000
75%         71.000000
max         90.000000
Name: availability_90, dtype: float64

-----------------------------------------------------------
no NaN in room_type:)
room_type
Entire home/apt    67921
Private room        5838
Hotel room           555
Shared room          265
Name: count, dtype: int64

-----------------------------------------------------------
- minimum_nights: 0% NaN !
- minimum_nights: 0.0% 0 !

count    74579.000000
mean         9.976039
std         39.012798
min          1.000000
25%          1.000000
50%          3.000000
75%          4.000000
max       1000.000000
Name: minimum_nights, dtype: float64

-----------------------------------------------------------
no NaN in instant_bookable:)
instant_bookable
f    56149
t    18430
Name: count, dtype: int64

-----------------------------------------------------------
no NaN in is_within_3km:)
is_within_3km
1    64912
0     9667
Name: count, dtype: int64

-----------------------------------------------------------
[SAVE] df_filtered saved to data_jo_3_filtered\listings_filtered.csv!

## host profil

In [16]:

importlib.reload(preprocess_listings)
from utils.preprocess_listings import group_mean_table_ttest
# host_vars= ['host_picture_url', 'host_identity_verified', 'number_of_reviews', 'host_is_superhost',
#            'review_scores_rating', 'has_rating', 'host_since', 'years_since_host', 'host_about', 
#            'has_host_about', 'lang', 'len', 'host_response_time', 'host_response_rate', 'has_response_rate',
#            'calculated_host_listings_count', 'professional_host']


group_col='host_is_superhost'

host_vars= ['number_of_reviews', 'review_scores_rating', 'has_rating', 
        'host_since', 'years_since_host', 'host_about', 'has_host_about', 'lang', 'len',
        'host_response_time', 'host_response_rate', 'has_response_rate',
        'professional_host']

proxy_obj_vars=['price', "availability_30", "number_of_reviews_l30d","booking_rate_l30d",
        "room_type", "minimum_nights","instant_bookable"]

# cols_tactics=['ouverture_mean',"authenticité_mean","sociabilité_mean", "auto_promotion_mean","exemplarité_mean",
#         "ouverture_weighted", "authenticité_weighted","sociabilité_weighted","auto_promotion_weighted","exemplarité_weighted",
#         ]

cols=host_vars + proxy_obj_vars
table = group_mean_table_ttest(df_filtered, cols, 
                               group_col="host_is_superhost", 
                               output_folder="desc_results")
display(table)

[INFO] ttest on 74579 lines.
group by : host_is_superhost
f    60941
t    13638
Name: count, dtype: int64

[WARNING]1 missing cols in df_input :
 booking_rate_l30d

[WARNING] non_numeric_cols:
 host_since; host_about; lang; host_response_time; room_type; instant_bookable

Table of Superhost and others in 13 dimensions:

[SAVE] table host csv saved to desc_results\table_host.csv!

[SAVE] table latex saved to desc_results\table_host_latex.tex!

                         Superhôte      Autres   ttest_p significance
number_of_reviews        51.815295    15.52815       0.0          ***
review_scores_rating      4.358714    2.800916       0.0          ***
has_rating                0.896026    0.597644       0.0          ***
years_since_host          7.583883    6.565071       0.0          ***
has_host_about            0.520824    0.413662       0.0          ***
len                      27.517891    25.05845       0.0          ***
host_response_rate        0.950125    0.626547       0.0          ***
has_response_rate         0.961798    0.677836       0.0          ***
professional_host         0.432981    0.333798       0.0          ***
price                   266.616073  294.101278  0.000032          ***
availability_30           9.562033   10.857715       0.0          ***
number_of_reviews_l30d    1.401085    0.545675       0.0          ***
minimum_nights            6.006013   10.864492       0.0          ***