In [ ]:
import sys, os, importlib, pathlib
from pathlib import Path
import pandas as pd
from datetime import datetime
sys.path.append(os.path.abspath('..'))

## my utils 
from utils import split_listings, preprocess_listings

## split > process > filter 
(data_raw> data_processed)

In [ ]:
## SPLIT+ process
importlib.reload(split_listings)
importlib.reload(preprocess_listings)
from utils.split_listings import split_change_stable
from utils.preprocess_listings import preprocess_host_variables, preprocess_obj_vars


#=========================input==============================

INPUT_FODLER=Path("../data_raw/")
path_Q1="../data_raw\listings_paris2403.csv"
path_Q2="../data_raw\listings_paris2406.csv"
path_Q3="../data_raw\listings_paris2409.csv"
YEAR=24
LOC="paris"
YM=2406


OUTPUT_FOLDER="../data_processed_paris"

##====================split+process===========================
df_split=split_change_stable(path_Q1, path_Q2, year=YEAR, threshold_text_sim=0.85, 
                        output_folder=OUTPUT_FOLDER, filename=f"listings_{LOC}{YM}_split.csv")


df_processed=preprocess_host_variables(df_split)

df_filtered=preprocess_obj_vars(df=df_processed, 
                        proxy_vars=['price',"availability_90"], 
                        get_boooking_rate_l30d=False, filtrate_by_booking_rate=False,#无输入时默认不按照booking筛选 
                        obj_vars=["room_type", 'property_type',"minimum_nights","instant_bookable"], 
                        threshold_km=3, 
                        cols_to_keep=None,
                        output_folder=OUTPUT_FOLDER, 
                        filename=f"listings_{LOC}{YM}_filtered.csv"
                        )

===================================INPUT DATA===================================
len df Q1: 84397
len df Q2: 95885
len df total : 180282

---------------------------------------listings count change----------------------------------------
new listings in Q2 19299(20.13%)
listings dispeared in Q2 : 7811(8.15%)
listings changed (in+out) in Q2:27110

---------------------------------------------BIO change---------------------------------------------
---------------------------------------------PIC change---------------------------------------------
----------------------------------split  changed and stable hosts-----------------------------------
[INFO] 3 criterions :
- NEW hosts enter between '24-01-01'~'24-06-30';
- Reactive hosts : host_since not in Q1/Q2; active not in Q1, but in Q2
=> ADD 'status_changed'-BIO change in Q2;
-PIC change in Q2
=> ADD 'sp_changed'
==> ADD 'is_changed'

[INFO] host status in Q2:
 status
old_host    81141
new_host    14744
Name: count, dtype: int64

[INFO] host BIO change in Q2: 1/0:host_about_changed
0    87046
1     8839
Name: count, dtype: int64

[INFO] PIC change in Q2: 1/0:host_picture_url_changed
0    72901
1    22984
Name: count, dtype: int64

[INFO] SP changed in Q2: 1/0:
sp_changed
0    72128
1    23757
Name: count, dtype: int64

[INFO] OVERALL changed : 23757; stable : 72128

[RUNTIME] done in 16.84 sec!

d:\Edu\SelfPresentation_Multimodal_airbnb\utils\split_listings.py:193: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['status_changed'] = (
d:\Edu\SelfPresentation_Multimodal_airbnb\utils\split_listings.py:198: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sp_changed'] = (
d:\Edu\SelfPresentation_Multimodal_airbnb\utils\split_listings.py:204: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['is_changed'] = (

✅[SAVE] dfQ2 split saved to ../data_processed\listings_paris2406_split.csv!


******************************HOST VARS******************************
PROCESS PIPELINE :
- host_has_profile_pic : fillna('f') if not f/t
- host_identity_verified: fillna('f') if not f/t
- host_is_sueprhost: check ONLY 't'/'f'; fillna('f')
- review_scores_rating: 34.0% NaN; fillna(mean), to numeric; ADD 'has_rating'
- host_since: ADD 'years_since_host' :float, 0.5-1 year=>1， 0-0.5 year => 0
- has_host_about: 'lang:en/fr/other_langs','len:int',
- host_response_time:40.0% NaN, fillna('no_response_time')
- host_response_rate:40.0% NaN, ADD 'has_response_rate' :1/0， fillna(0)
- calculated_host_listings_count : ADD 'professional_host:1/0', count>1

[INFO] missing review scores are filled by mean :4.724711210889053

==========================HOST VARS================================
16 IMPO VARS:['host_picture_url', 'host_identity_verified', 'number_of_reviews', 'host_is_superhost', 'review_scores_rating', 'has_rating', 'host_since', 'years_since_host', 'host_about', 'lang', 'len', 'host_response_time', 'host_response_rate', 'has_response_rate', 'calculated_host_listings_count', 'professional_host']


================= BALN PROCESSED VARIABLES =====================
[INFO] statictic description on df (95885 lines):
host_picture_url ; host_identity_verified ; number_of_reviews ; host_is_superhost ; review_scores_rating ; has_rating ; host_since ; years_since_host ; host_about ; lang ; len ; host_response_time ; host_response_rate ; has_response_rate ; calculated_host_listings_count ; professional_host

[WARINNG] NaN in host_picture_url!!
host_picture_url
https://a0.muscache.com/defaults/user_pic-225x225.png?v=3                                                                                3727
https://a0.muscache.com/im/pictures/user/0afb4368-deff-4ea7-b48e-d1ef5a40ea9a.jpg?aki_policy=profile_x_medium                             730
https://a0.muscache.com/im/pictures/user/cefcf382-a8fe-4348-9bba-ae00462784ca.jpg?aki_policy=profile_x_medium                             497
https://a0.muscache.com/im/pictures/user/f1221c8c-c1be-4947-aaa7-4fca4221b75c.jpg?aki_policy=profile_x_medium                             426
https://a0.muscache.com/im/pictures/user/User-50978178/original/f8b585d7-a644-46a3-bb64-7dc6ef49fde2.jpeg?aki_policy=profile_x_medium     307
                                                                                                                                         ...
https://a0.muscache.com/im/users/108444/profile_pic/1310919783/original.jpg?aki_policy=profile_x_medium                                     1
https://a0.muscache.com/im/pictures/user/User-532468/original/b7887167-60ae-4048-9bfc-3bac666ec234.jpeg?aki_policy=profile_x_medium         1
https://a0.muscache.com/im/pictures/user/User-107514/original/211929e2-643f-452f-ae1a-64511f78c0b6.jpeg?aki_policy=profile_x_medium         1
https://a0.muscache.com/im/users/546512/profile_pic/1304181922/original.jpg?aki_policy=profile_x_medium                                     1
https://a0.muscache.com/im/pictures/user/bd80fced-7c1e-4b41-9aec-0ef83f1ee107.jpg?aki_policy=profile_x_medium                               1
Name: count, Length: 68562, dtype: int64

-----------------------------------------------------------
no NaN in host_identity_verified:)
host_identity_verified
t    86326
f     9559
Name: count, dtype: int64

-----------------------------------------------------------
- number_of_reviews: 0% NaN !
- number_of_reviews: 34.0% 0 !

count    95885.000000
mean        19.888189
std         52.040205
min          0.000000
25%          0.000000
50%          3.000000
75%         18.000000
max       3067.000000
Name: number_of_reviews, dtype: float64

-----------------------------------------------------------
no NaN in host_is_superhost:)
host_is_superhost
f    81109
t    14776
Name: count, dtype: int64

-----------------------------------------------------------
- review_scores_rating: 0% NaN !
- review_scores_rating: 0.0% 0 !

count    95885.000000
mean         4.760056
std          0.319556
min          0.000000
25%          4.750000
50%          4.830000
75%          4.920000
max          5.000000
Name: review_scores_rating, dtype: float64

-----------------------------------------------------------
no NaN in has_rating:)
has_rating
1    63697
0    32188
Name: count, dtype: int64

-----------------------------------------------------------
- host_since: 0.0% NaN !
- host_since: 0.0% 0 !

count                            95877
mean     2017-05-21 19:04:17.166995200
min                2008-08-30 00:00:00
25%                2014-08-06 00:00:00
50%                2016-05-01 00:00:00
75%                2019-12-08 00:00:00
max                2024-06-09 00:00:00
Name: host_since, dtype: object

-----------------------------------------------------------
- years_since_host: 0% NaN !
- years_since_host: 5.0% 0 !

count    95885.000000
mean         7.055994
std          3.635189
min          0.000000
25%          5.000000
50%          8.000000
75%         10.000000
max         16.000000
Name: years_since_host, dtype: float64

-----------------------------------------------------------
[WARINNG] NaN in host_about!!
host_about
NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                54827
We’re Blueground, a global proptech company with several thousand move-in-ready apartments in a growing number of major cities around the world. With flexible terms and homes in vibrant, centrally based neighborhoods, you’ll feel at home and free to roam for as long as you want — a month, a year, or longer. \n\nEach apartment is thoughtfully designed with exclusive furnishings, fully equipped kitchens, and incredible amenities – making every day a five-star experience. From day one, you’ll enjoy high-speed Wi-Fi, premium linens, and smart home entertainment. Plus, access to pools, gyms, and outdoor spaces in select buildings.\n\nWhy stress over your apartment? We provide a hassle-free alternative — a consistent, quality guest experience that starts even before you arrive. Because we let you book our most up-to-date apartment listings online, confirm with a click, pay securely, and check in easily. \n\nDuring your stay\nUpon arrival, you’ll either be greeted personally by a Blueground team member or given self-check-in instructions. The entire apartment is yours! You’ll enjoy reliable support via email, phone, and our Guest App, where you can request everything from a home cleaning to extra towels. \n\nWe’ll share all details upon confirmation of your stay.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         730
Greetings from the Veeve team!\n\n\nVeeve manage the largest collection of homes to rent for short stays in London since 2011, launching in Paris in 2017. Our rental homes are predominantly privately-owned, lived-in homes in vibrant neighbourhoods. Thanks to our fully managed service, when you stay in a Veeve property you can benefit from the spaciousness, personal style and relaxed feel of a home – but with all the amenities of a hotel.\n\n\nOnce a booking is confirmed our Customer Service team will become your main point of contact and get in touch with you to organise your arrival at the property (including airport transfers, upon request); after which our on-the-ground management team will look after all aspects of your stay, with in-stay support available to help with any queries.\n\n\nWe have strict cleanliness guidelines for our cleaners and all staff who enter our properties and have reinforced existing cleaning procedures in line with official WHO, British and French government guidance.\n\n\nAs always, our team ensure that all properties are cleaned to a professional standard before and after each stay, with increased focus on touch-point cleaning (door handles, kitchen surfaces, kettles, taps etc.).\n\n All staff who enter properties will follow the below procedures:\n \n\n- Carry and regularly use alcohol-based hand rub\n- Sanitise their mobile phones \n- Focus extra attention when cleaning key touch-point areas (door handles, kitchen surfaces, kettles, taps etc.)\n- Wear protective gear where appropriate\n- Wash and disinfect work shoes\n\n\nWe might be able to arrange for property viewings, upon request, for stays of over 28 nights. \n\nPlease be aware once a booking is confirmed you will be required to complete a Rental Agreement and also  ID verification via our partners Superhog. This is mandatory for all our stays and in accordance to short lets requirements with Veeve.\n\nIf you have any questions, please do not hesitate to contact us and we will be sure to answer you promptly.      497
Bonjour, \nExperts Airbnb depuis 10 ans, nous serons ravis de vous apporter notre aide de la création de votre annonce jusqu'à la gestion de votre logement.\n\nNous sommes disponibles de 10:00 à 18:00                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             426
At GuestReady, we're on a mission to redefine modern hospitality. We specialise in helping hosts deliver outstanding experiences to their guests worldwide. With years of hospitality experience, we're dedicated to providing an exceptional experience. Let us help you find the perfect place for an unforgettable stay!                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          332
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ...
Bonjour, je démarre la location de mon logement pendant mes périodes d’absence. \nParisien depuis 2011. \nJ’aurai plaisir à vous accueillir chez moi ainsi qu'à vous partager mes recommandations suivant vos envies !                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 1

In [ ]:
### london
import os, sys, importlib, pathlib
import pandas as pd
sys.path.append(os.path.abspath(".."))
from utils import split_listings, preprocess_listings

importlib.reload(split_listings)
importlib.reload(preprocess_listings)
from utils.split_listings import split_change_stable
from utils.preprocess_listings import preprocess_host_variables, preprocess_obj_vars


#=========================input==============================
path_Q1="../data_raw\listings_london2403.csv"
path_Q2="../data_raw\listings_london2406.csv"
path_Q3="../data_raw\listings_london2409.csv"
dfQ3=pd.read_csv(path_Q3)

# YEAR=24
LOC="london"
YM=2406
OUTPUT_FOLDER_DATA="../data_processed_london"


##====================split+process===========================
df_split=split_change_stable(path_Q1, path_Q2, year=YEAR, threshold_text_sim=0.85, 
                        output_folder=OUTPUT_FOLDER_DATA, filename=f"listings_{LOC}{YM}_split.csv")
df_processed=preprocess_host_variables(df_split)


df_filtered=preprocess_obj_vars(df=df_processed, df_nextQ=dfQ3, proxy_vars=['price',"availability_30","availability_90"], 
                        get_booking_rate_l30d=False, filtrate_by_booking_rate_l30d=False,#无输入时默认不按照booking筛选 
                        get_booking_rate_l90d=True, filtrate_by_booking_rate_l90d=True,
                        obj_vars=["room_type", 'property_type',"minimum_nights","instant_bookable"], 
                        threshold_km=3, 
                        output_folder=OUTPUT_FOLDER_DATA, filename=f"listings_{LOC}{YM}_filtered.csv")

===================================INPUT DATA===================================
len df Q1: 90852
len df Q2: 93481
len df total : 184333

---------------------------------------listings count change----------------------------------------
new listings in Q2 14777(15.81%)
listings dispeared in Q2 : 12148(13.00%)
listings changed (in+out) in Q2:26925

---------------------------------------------BIO change---------------------------------------------
---------------------------------------------PIC change---------------------------------------------
----------------------------------split  changed and stable hosts-----------------------------------
[INFO] 3 criterions :
- NEW hosts enter between '24-01-01'~'24-06-30';
- Reactive hosts : host_since not in Q1/Q2; active not in Q1, but in Q2
=> ADD 'status_changed'-BIO change in Q2;
-PIC change in Q2
=> ADD 'sp_changed'
==> ADD 'is_changed'

[INFO] host status in Q2:
 status
old_host    86357
new_host     7124
Name: count, dtype: int64

[INFO] host BIO change in Q2: 1/0:host_about_changed
0    84978
1     8503
Name: count, dtype: int64

[INFO] PIC change in Q2: 1/0:host_picture_url_changed
0    76659
1    16822
Name: count, dtype: int64

[INFO] SP changed in Q2: 1/0:
sp_changed
0    75727
1    17754
Name: count, dtype: int64

[INFO] OVERALL changed : 17754; stable : 75727

[RUNTIME] done in 13.78 sec!

d:\Edu\SelfPresentation_Multimodal_airbnb\utils\split_listings.py:193: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['status_changed'] = (
d:\Edu\SelfPresentation_Multimodal_airbnb\utils\split_listings.py:198: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sp_changed'] = (
d:\Edu\SelfPresentation_Multimodal_airbnb\utils\split_listings.py:204: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['is_changed'] = (

✅[SAVE] dfQ2 split saved to ../data_processed_london\listings_london2406_split.csv!


******************************HOST VARS******************************
PROCESS PIPELINE :
- host_has_profile_pic : fillna('f') if not f/t
- host_identity_verified: fillna('f') if not f/t
- host_is_sueprhost: check ONLY 't'/'f'; fillna('f')
- review_scores_rating: 26.0% NaN; fillna(mean), to numeric; ADD 'has_rating'
- host_since: ADD 'years_since_host' :float, 0.5-1 year=>1， 0-0.5 year => 0
- has_host_about: 'lang:en/fr/other_langs','len:int',
- host_response_time:33.0% NaN, fillna('no_response_time')
- host_response_rate:33.0% NaN, ADD 'has_response_rate' :1/0， fillna(0)
- calculated_host_listings_count : ADD 'professional_host:1/0', count>1

[INFO] missing review scores are filled by mean :4.701566068752819

==========================HOST VARS================================
16 IMPO VARS:['host_picture_url', 'host_identity_verified', 'number_of_reviews', 'host_is_superhost', 'review_scores_rating', 'has_rating', 'host_since', 'years_since_host', 'host_about', 'lang', 'len', 'host_response_time', 'host_response_rate', 'has_response_rate', 'calculated_host_listings_count', 'professional_host']


================= BALN PROCESSED VARIABLES =====================
[INFO] statictic description on df (93481 lines):
host_picture_url ; host_identity_verified ; number_of_reviews ; host_is_superhost ; review_scores_rating ; has_rating ; host_since ; years_since_host ; host_about ; lang ; len ; host_response_time ; host_response_rate ; has_response_rate ; calculated_host_listings_count ; professional_host

[WARINNG] NaN in host_picture_url!!
host_picture_url
https://a0.muscache.com/defaults/user_pic-225x225.png?v=3                                                        3634
https://a0.muscache.com/im/pictures/user/941760a3-5428-43f4-b947-75b2b45aaf7d.jpg?aki_policy=profile_x_medium     441
https://a0.muscache.com/im/pictures/user/cefcf382-a8fe-4348-9bba-ae00462784ca.jpg?aki_policy=profile_x_medium     390
https://a0.muscache.com/im/users/28820321/profile_pic/1444330784/original.jpg?aki_policy=profile_x_medium         276
https://a0.muscache.com/im/pictures/user/a4617638-5d7d-4efb-807c-8fa545f1a4ab.jpg?aki_policy=profile_x_medium     248
                                                                                                                 ...
https://a0.muscache.com/im/pictures/user/fe9ebfd8-3b7d-4f44-99e3-40dbf89f121f.jpg?aki_policy=profile_x_medium       1
https://a0.muscache.com/im/pictures/user/f8e1b2c4-4254-4617-a6d0-f9a653440a76.jpg?aki_policy=profile_x_medium       1
https://a0.muscache.com/im/pictures/user/976ea99e-af76-4743-9d88-992d747dcef2.jpg?aki_policy=profile_x_medium       1
https://a0.muscache.com/im/pictures/user/58952c7e-08c3-4512-a103-90892732a41b.jpg?aki_policy=profile_x_medium       1
https://a0.muscache.com/im/users/17032526/profile_pic/1403273745/original.jpg?aki_policy=profile_x_medium           1
Name: count, Length: 53830, dtype: int64

-----------------------------------------------------------
no NaN in host_identity_verified:)
host_identity_verified
t    81902
f    11579
Name: count, dtype: int64

-----------------------------------------------------------
- number_of_reviews: 0% NaN !
- number_of_reviews: 26.0% 0 !

count    93481.000000
mean        19.080252
std         45.767345
min          0.000000
25%          0.000000
50%          4.000000
75%         18.000000
max       1678.000000
Name: number_of_reviews, dtype: float64

-----------------------------------------------------------
no NaN in host_is_superhost:)
host_is_superhost
f    76401
t    17080
Name: count, dtype: int64

-----------------------------------------------------------
- review_scores_rating: 0% NaN !
- review_scores_rating: 0.0% 0 !

count    93481.000000
mean         4.738206
std          0.391936
min          0.000000
25%          4.700000
50%          4.840000
75%          4.960000
max          5.000000
Name: review_scores_rating, dtype: float64

-----------------------------------------------------------
no NaN in has_rating:)
has_rating
1    68739
0    24742
Name: count, dtype: int64

-----------------------------------------------------------
- host_since: 0.0% NaN !
- host_since: 0.0% 0 !

count                            93475
mean     2017-07-03 09:33:34.883124224
min                2008-08-28 00:00:00
25%                2014-11-30 00:00:00
50%                2016-08-31 00:00:00
75%                2019-12-03 00:00:00
max                2024-06-12 00:00:00
Name: host_since, dtype: object

-----------------------------------------------------------
- years_since_host: 0% NaN !
- years_since_host: 3.0% 0 !

count    93481.000000
mean         6.946428
std          3.524481
min          0.000000
25%          5.000000
50%          8.000000
75%         10.000000
max         16.000000
Name: years_since_host, dtype: float64

-----------------------------------------------------------
[WARINNG] NaN in host_about!!
host_about
NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                45684
We are your professional property manager that cares about giving the best guest experience: that’s why our friendly, round-the-clock Support Team is here to help! We’ll tell you everything you need to know before check-in, and answer any questions during your stay.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           526
We’re Blueground, a global proptech company with several thousand move-in-ready apartments in a growing number of major cities around the world. With flexible terms and homes in vibrant, centrally based neighborhoods, you’ll feel at home and free to roam for as long as you want — a month, a year, or longer. \n\nEach apartment is thoughtfully designed with exclusive furnishings, fully equipped kitchens, and incredible amenities – making every day a five-star experience. From day one, you’ll enjoy high-speed Wi-Fi, premium linens, and smart home entertainment. Plus, access to pools, gyms, and outdoor spaces in select buildings.\n\nWhy stress over your apartment? We provide a hassle-free alternative — a consistent, quality guest experience that starts even before you arrive. Because we let you book our most up-to-date apartment listings online, confirm with a click, pay securely, and check in easily. \n\nDuring your stay\nUpon arrival, you’ll either be greeted personally by a Blueground team member or given self-check-in instructions. The entire apartment is yours! You’ll enjoy reliable support via email, phone, and our Guest App, where you can request everything from a home cleaning to extra towels. \n\nWe’ll share all details upon confirmation of your stay.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         441
Greetings from the Veeve team!\n\n\nVeeve manage the largest collection of homes to rent for short stays in London since 2011, launching in Paris in 2017. Our rental homes are predominantly privately-owned, lived-in homes in vibrant neighbourhoods. Thanks to our fully managed service, when you stay in a Veeve property you can benefit from the spaciousness, personal style and relaxed feel of a home – but with all the amenities of a hotel.\n\n\nOnce a booking is confirmed our Customer Service team will become your main point of contact and get in touch with you to organise your arrival at the property (including airport transfers, upon request); after which our on-the-ground management team will look after all aspects of your stay, with in-stay support available to help with any queries.\n\n\nWe have strict cleanliness guidelines for our cleaners and all staff who enter our properties and have reinforced existing cleaning procedures in line with official WHO, British and French government guidance.\n\n\nAs always, our team ensure that all properties are cleaned to a professional standard before and after each stay, with increased focus on touch-point cleaning (door handles, kitchen surfaces, kettles, taps etc.).\n\n All staff who enter properties will follow the below procedures:\n \n\n- Carry and regularly use alcohol-based hand rub\n- Sanitise their mobile phones \n- Focus extra attention when cleaning key touch-point areas (door handles, kitchen surfaces, kettles, taps etc.)\n- Wear protective gear where appropriate\n- Wash and disinfect work shoes\n\n\nWe might be able to arrange for property viewings, upon request, for stays of over 28 nights. \n\nPlease be aware once a booking is confirmed you will be required to complete a Rental Agreement and also  ID verification via our partners Superhog. This is mandatory for all our stays and in accordance to short lets requirements with Veeve.\n\nIf you have any questions, please do not hesitate to contact us and we will be sure to answer you promptly.      390
I moved to London to follow my love who is a Londoner, I have a 4 years old daughter and two cats. we live in a beautiful house surrounded by parks and trees in Muswell Hill.\n\nThe Airbnb experience has been very positive and from that experience I set up a company called HelloGuest to provide excellent hassle-free Airbnb management services for short stay rental properties in London and across all the UK advertised on Airbnb.\n\nOur services cover everything from full property management (guest communication, check-in & out, cleaning & laundry, manage the listing, 24/7 support service, etc) to partly managed or individual services depending on your needs.\n\nOur aim is to provide professional services for high quality properties to deliver an excellent guest experience.\n\nWe are here to help, so please get in touch with any questions you have.\n\n                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       276
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ...
We are a family from West London - Dan, Natalie, Lenny (6) and Luca (2)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                1

## unique + sample (data_processed> data_unique)

In [ ]:
## dropna drop duplicates

df_unique=df_filtered.copy()
print(len(df_filtered))
df_unique=df_unique.dropna(subset="host_about").drop_duplicates(subset="host_about")
print(len(df_unique))
df_unique_sample=df_unique.sample(10)

df_unique_sample.to_csv(f"../data_processed_london/listings_london2406_unique{len(df_unique_sample)}.csv", index=False)



# OUTPUT_FOLDER_UNIQUE="../data_unique"
# os.makedirs(OUTPUT_FOLDER_UNIQUE, exist_ok=True)
# outpath_unique=os.path.join(OUTPUT_FOLDER_UNIQUE, f"listings_{LOC}{YM}_unique{len(df_unique)}.csv")
# df_unique.to_csv(outpath_unique, index=False)

49856
11966

## zsc + merge (data_unqiue> output_zsc > data_processed)

In [ ]:
import os, sys, importlib
sys.path.append(os.path.abspath(".."))

from utils import zsc
importlib.reload(zsc)
from utils.zsc import run_zsc,merge_by_host_about


# from unique to output zsc(df_zsc, run)
PATH_DF_UNIQUE="../data_unique\listings_paris2406_unique5.csv"
OUTPATH_ZSC_RESULT="../output_zsc/listings_paris2406_bge5.csv"

df_items=run_zsc(
    path_df_unique=PATH_DF_UNIQUE,
    dict_items=None,
    model_name="MoritzLaurer/bge-m3-zeroshot-v2.0",
    by_lang=True,
    outpath_zsc_result=OUTPATH_ZSC_RESULT,
    save_interval=5,# save every 
    log=True)


# from output zsc& data_processed to data_processed
# .filtered=> .items(len)
PATH_DF_FILTERED="../data_processed\listings_paris2406_filtered.csv"
df_items=merge_by_host_about(path_df_zsc=OUTPATH_ZSC_RESULT, 
                             path_df_filtered=PATH_DF_FILTERED, 
                        save=True, output_folder='../data_processed')

----------------------------------load df_unique & previous result----------------------------------
[INFO] first zsc!
---------------------------------------------load model---------------------------------------------

Device set to use cpu

[MODEL] MoritzLaurer/bge-m3-zeroshot-v2.0 loaded in 1.38 sec !
-----------------------------------df_todo ==ZSC==> results_list------------------------------------
[INFO] zsc by lang !

ZSC: 100%|██████████| 5/5 [02:04<00:00, 24.89s/it]

✔ [SAVE] 5 / 5 checkpoint saved to ../output_zsc/listings_paris2406_bge5.csv!

✅ [SAVE] Final save: 5 rows to ../output_zsc/listings_paris2406_bge5.csv
[SUCCESS] ZSC sur 5 textes avec 22 EN labels/22 FR labels
par MoritzLaurer/bge-m3-zeroshot-v2.0 prend 124.47 sec !
✅ [SAVE] log saved to ../output_zsc\run_20251219.txt!

,id,text,responsive,attentive to needs,willing to help,thoughtful service,open to different cultures,divers interests,welcoming,cosmopolitan,...,life experiences,travel with Airbnb,enjoy life,fan of Airbnb,personal life,Airbnb community,love Airbnb,hobbies,meet new people,cultural exchange
0,1014484986670438487,Researcher in Biophysics,0.242026,0.126138,0.047382,0.038865,0.033621,0.033086,0.007191,0.006552,...,0.000481,0.000326,0.000299,0.000290,0.000288,0.000286,0.000285,0.000282,0.000274,0.000266
1,1160702796047135233,Je loue mon appartement T2 du 14 juin au 14 ju...,0.638497,0.423413,0.086016,0.503174,0.423875,0.488299,0.784112,0.031351,...,0.802246,0.490693,0.012124,0.064241,0.555089,0.772101,0.332581,0.002642,0.001034,0.023331
2,35091166,Stéphanie Fournier / Villa Marlise,0.322659,0.210442,0.224735,0.190423,0.209066,0.037786,0.501129,0.012360,...,0.037715,0.408321,0.003664,0.018125,0.201028,0.043569,0.056757,0.002941,0.004565,0.580114
3,779768699796832035,Bienvenue chez moi !,0.336631,0.322046,0.150903,0.175256,0.097390,0.003559,0.996577,0.162579,...,0.053949,0.665900,0.033717,0.196209,0.034424,0.704364,0.437418,0.000806,0.731778,0.003714
4,1587440,Jérémy et Matthieu sont en couple depuis 3 ans...,0.506973,0.535273,0.311008,0.093099,0.562837,0.094845,0.995470,0.762070,...,0.839273,0.105579,0.330471,0.272266,0.621857,0.602025,0.094678,0.315789,0.040731,0.117876

# test on paris:

In [2]:
df6=pd.read_csv("data_jo\listings_paris2406.csv")
print("jo paris 06:",len(df6))

df9=pd.read_csv("data_jo\listings_paris2409.csv")
print("jo paris 09:", len(df9))


df6['scraped_date'] = '2024Q2'
df9['scraped_date'] = '2024Q3'
dfparis = pd.concat([df6, df9], ignore_index=True)
print(len(dfparis))

# dfparis=pd.read_csv("data_jo_processed/listings_jo_paris.csv")
# print(len(dfparis))

jo paris 06: 95885
jo paris 09: 95461
191346

In [138]:
#描述房东数量变化：
hosts_in = set(df9['host_id']) - set(df6['host_id']) # 9月有，但6月没有
hosts_out = set(df6['host_id']) - set(df9['host_id']) #6月有，但9月没有
hosts_io= set(df9['host_id']) ^ set(df6['host_id']) # 属于 6月 或 9月，但不同时属于两者;所有变化的房东（新增 + 消失）
print(f'new hosts after JO : {len(hosts_in)}({len(hosts_in)*100/len(df9):.2f}%)')
print(f'hosts dispeared after JO : {len(hosts_out)}({len(hosts_out)*100/len(df9):.2f}%)')
print(f"host changed during JO :{len(hosts_io)}")

new hosts after JO : 5897(6.18%)
hosts dispeared after JO : 7024(7.36%)
host changed during JO :12921

In [139]:
#描述房源数量变化
hosts_in = set(df9['id']) - set(df6['id']) # 9月有，但6月没有
hosts_out = set(df6['id']) - set(df9['id']) #6月有，但9月没有
hosts_io= set(df9['id']) ^ set(df6['id']) # 属于 6月 或 9月，但不同时属于两者;所有变化的房东（新增 + 消失）
print(f'new listings after JO : {len(hosts_in)}({len(hosts_in)*100/len(df9):.2f}%)')
print(f'listings dispeared after JO : {len(hosts_out)}({len(hosts_out)*100/len(df9):.2f}%)')
print(f"listings changed during JO :{len(hosts_io)}")

new listings after JO : 9882(10.35%)
listings dispeared after JO : 10306(10.80%)
listings changed during JO :20188

In [8]:
#增加status列：
# 统计每个房东在每个时期的房源数量
hosts6 = df6.groupby('host_id').size().reset_index(name='listings_06')
hosts9 = df9.groupby('host_id').size().reset_index(name='listings_09')

# 合并两个时期
merged = hosts6.merge(hosts9, on='host_id', how='outer')

# 分类:新房东，消失房东，listings增加/减少/不变
merged['status'] = merged.apply(
    lambda r:
        'new_host' if pd.isna(r['listings_06']) else
        'disappeared_host' if pd.isna(r['listings_09']) else
        ('expanded' if r['listings_09'] > r['listings_06'] else
         'reduced' if r['listings_09'] < r['listings_06'] else
         'no_change'),
    axis=1
)

print(merged.head())
print(len(merged))
print(merged.status.value_counts())

dfparis=dfparis.merge(merged[['host_id','status']], left_on='host_id', right_on='host_id',how='left')
print(len(dfparis))
display(dfparis.head())

   host_id  listings_06  listings_09     status
0     2626          3.0          1.0    reduced
1     2883          NaN          2.0   new_host
2     3631          1.0          1.0  no_change
3     5468          1.0          1.0  no_change
4     6792          8.0         11.0   expanded
77876
status
no_change           63061
disappeared_host     7024
new_host             5897
reduced               948
expanded              946
Name: count, dtype: int64
191346

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,scraped_date,host_about_q2,host_about_changed,host_picture_url_q2,host_picture_url_changed,status
0,80260,https://www.airbnb.com/rooms/80260,20240610195007,2024-06-13,previous scrape,Nice studio in Jourdain's village,NaN,NaN,https://a0.muscache.com/pictures/716553/6c14f2...,333548,...,1,0,0,1.29,2024Q2,"My name is Charlotte, I'm 26 and I study cinem...",NaN,https://a0.muscache.com/im/users/333548/profil...,NaN,no_change
1,3109,https://www.airbnb.com/rooms/3109,20240610195007,2024-06-12,city scrape,zen and calm,Lovely Appartment with one bedroom with a Quee...,Good restaurants<br />very close the Montparna...,https://a0.muscache.com/pictures/miso/Hosting-...,3631,...,1,0,0,0.05,2024Q2,NaN,NaN,https://a0.muscache.com/im/users/3631/profile_...,NaN,no_change
2,80301,https://www.airbnb.com/rooms/80301,20240610195007,2024-06-13,city scrape,toits de Paris,"On the top,sharing my space,you have your bedr...","SAFE neighborhood,late bus and subway,velibe(b...",https://a0.muscache.com/pictures/742354/2e66b9...,433758,...,1,1,0,0.27,2024Q2,"Doctorat Sorbonne 1,Litterature sciences huma...",NaN,https://a0.muscache.com/im/users/433758/profil...,NaN,no_change
3,5396,https://www.airbnb.com/rooms/5396,20240610195007,2024-06-13,city scrape,Your perfect Paris studio on Île Saint-Louis,"NEW SOFA-BED SINCE JUNE 2023, Please disregard...","You are within walking distance to the Louvre,...",https://a0.muscache.com/pictures/52413/f9bf76f...,7903,...,1,0,0,2.21,2024Q2,We have spent a lot of time traveling for work...,NaN,https://a0.muscache.com/im/users/7903/profile_...,NaN,no_change
4,7397,https://www.airbnb.com/rooms/7397,20240610195007,2024-06-13,city scrape,MARAIS - 2ROOMS APT - 2/4 PEOPLE,"VERY CONVENIENT, WITH THE BEST LOCATION !",NaN,https://a0.muscache.com/pictures/67928287/330b...,2626,...,3,0,0,2.21,2024Q2,"I am a writer,54, author of novels, books of l...",NaN,https://a0.muscache.com/im/pictures/user/ad6a9...,NaN,reduced

In [3]:
import pandas as pd
import numpy as np


if 'host_about_q2' not in dfparis:
    df_q2 = dfparis[dfparis['scraped_date'] == '2024Q2'][['host_id', 'id', 'host_about']]
    df_q2 = df_q2.rename(columns={'host_about': 'host_about_q2'})
    dfparis = dfparis.merge(df_q2, on=['host_id', 'id'], how='left')


# 计算文本相似度（使用 difflib.SequenceMatcher）
from difflib import SequenceMatcher
def text_similarity(a, b):
    if pd.isna(a) or pd.isna(b):
        return None
    return SequenceMatcher(None, str(a), str(b)).ratio()

# 标记 Q3 相对于 Q2 的变化
def host_about_change(row, threshold=0.85):
    """
    没改动/例外都被填为nan （包括所有Q2房东）
    新房东/新文本/新bio填1或sim
    """
    if row['scraped_date'] != '2024Q3':
        return None  # 只对 Q3 标记
    if pd.isna(row['host_about_q2']) and pd.notna(row['host_about']):
        return 1  # Q2 没有文本，Q3 新增文本或新房东
    if pd.notna(row['host_about_q2']) and pd.notna(row['host_about']):#老房东&bio不为空# row['host_about'] != row['host_about_q2']:
        sim= text_similarity(row['host_about_q2'], row['host_about']) 
        if sim < threshold:## 老文本有明显变化
            return sim 
        else:
            return None#无明显改变是就填NAN
    return None  # 其他情况

if "host_about_change" not in dfparis:
    dfparis['host_about_changed'] = dfparis.apply(host_about_change, axis=1)

# 查看 Q3 中变化统计：没改动都被填为nan，新房东/新文本/新bio填1或sim:
print(dfparis.host_about_changed.notna().value_counts())
print(dfparis.host_about_changed.value_counts())


#有5k明显改变，其中4k是房东或者新添加文本

host_about_changed
False    186108
True       5238
Name: count, dtype: int64
host_about_changed
1.000000    4275
0.175573     336
0.020240     146
0.089844      33
0.289762      28
            ...
0.014634       1
0.218810       1
0.785083       1
0.318408       1
0.818182       1
Name: count, Length: 274, dtype: int64

In [4]:
if "host_picture_url_q2" not in dfparis:
    df_q2 = dfparis[dfparis['scraped_date'] == '2024Q2'][['host_id', 'id', 'host_picture_url']]
    df_q2 = df_q2.rename(columns={'host_picture_url': 'host_picture_url_q2'})
    dfparis = dfparis.merge(df_q2, on=['host_id', 'id'], how='left')


# 标记 Q3 相对于 Q2 的变化
def host_picture_url_change(row):
    if row['scraped_date'] != '2024Q3':
        return None # 只对 Q3 标记
    if pd.isna(row['host_picture_url_q2']) and pd.notna(row['host_picture_url']):
        return 1  # Q2 没有文本，Q3 新增文本
    if pd.notna(row['host_picture_url_q2']) and pd.notna(row['host_picture_url']) and row['host_picture_url'] != row['host_picture_url_q2']:
        return 1  # 老文本被修改
    return None  # 其他情况

if "host_picture_url_changed" not in dfparis:
    dfparis['host_picture_url_changed'] = dfparis.apply(host_picture_url_change, axis=1)

# 查看 Q3 变化统计
print(dfparis.host_picture_url_changed.notna().value_counts())
print(dfparis.host_picture_url_changed.value_counts())

#12K房东修改了照片

host_picture_url_changed
False    178811
True      12535
Name: count, dtype: int64
host_picture_url_changed
1.0    12535
Name: count, dtype: int64

In [9]:
display(dfparis.head())
dfparis.to_csv("data_jo_processed/listings_jo_paris.csv",index=False)

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,scraped_date,host_about_q2,host_about_changed,host_picture_url_q2,host_picture_url_changed,status
0,80260,https://www.airbnb.com/rooms/80260,20240610195007,2024-06-13,previous scrape,Nice studio in Jourdain's village,NaN,NaN,https://a0.muscache.com/pictures/716553/6c14f2...,333548,...,1,0,0,1.29,2024Q2,"My name is Charlotte, I'm 26 and I study cinem...",NaN,https://a0.muscache.com/im/users/333548/profil...,NaN,no_change
1,3109,https://www.airbnb.com/rooms/3109,20240610195007,2024-06-12,city scrape,zen and calm,Lovely Appartment with one bedroom with a Quee...,Good restaurants<br />very close the Montparna...,https://a0.muscache.com/pictures/miso/Hosting-...,3631,...,1,0,0,0.05,2024Q2,NaN,NaN,https://a0.muscache.com/im/users/3631/profile_...,NaN,no_change
2,80301,https://www.airbnb.com/rooms/80301,20240610195007,2024-06-13,city scrape,toits de Paris,"On the top,sharing my space,you have your bedr...","SAFE neighborhood,late bus and subway,velibe(b...",https://a0.muscache.com/pictures/742354/2e66b9...,433758,...,1,1,0,0.27,2024Q2,"Doctorat Sorbonne 1,Litterature sciences huma...",NaN,https://a0.muscache.com/im/users/433758/profil...,NaN,no_change
3,5396,https://www.airbnb.com/rooms/5396,20240610195007,2024-06-13,city scrape,Your perfect Paris studio on Île Saint-Louis,"NEW SOFA-BED SINCE JUNE 2023, Please disregard...","You are within walking distance to the Louvre,...",https://a0.muscache.com/pictures/52413/f9bf76f...,7903,...,1,0,0,2.21,2024Q2,We have spent a lot of time traveling for work...,NaN,https://a0.muscache.com/im/users/7903/profile_...,NaN,no_change
4,7397,https://www.airbnb.com/rooms/7397,20240610195007,2024-06-13,city scrape,MARAIS - 2ROOMS APT - 2/4 PEOPLE,"VERY CONVENIENT, WITH THE BEST LOCATION !",NaN,https://a0.muscache.com/pictures/67928287/330b...,2626,...,3,0,0,2.21,2024Q2,"I am a writer,54, author of novels, books of l...",NaN,https://a0.muscache.com/im/pictures/user/ad6a9...,NaN,reduced

In [10]:
df_change=dfparis[(dfparis['status']=='new_host')|(dfparis['status']=='expanded')|(dfparis['host_about_changed']==1)|(dfparis['host_picture_url_changed']==1)]
df_stable = dfparis[~dfparis['host_id'].isin(df_change['host_id'])]#.isin() 来做“是否在某个列表中”的列级比较，然后加 ~ 表示取反。
print(df_change.host_about.notna().value_counts())
print(df_stable.host_about.notna().value_counts())
print(f"len change: {len(df_change)}")
print(f"len stable: {len(df_stable)}")

host_about
True     16198
False    14156
Name: count, dtype: int64
host_about
False    90445
True     58638
Name: count, dtype: int64
len change: 30354
len stable: 149083

In [151]:
print(df_change.host_about.notna().value_counts())
print(df_stable.host_about.notna().value_counts())

host_about
True     16198
False    14156
Name: count, dtype: int64
host_about
False    90445
True     58638
Name: count, dtype: int64