In [1]:
import os, sys, importlib
sys.path.append(os.path.abspath(".."))
import json
import pandas as pd

## tactics dict

## face results all 2306-2312-2406

In [7]:
path_json=r"../B_images\images\results\face_london_2312.json"
with open (path_json, 'r', encoding="utf-8") as f:
    result=json.load(f)

In [23]:
results_dir=r"../B_images\images\results"
results=[]

for f in [f for f in os.listdir(results_dir) if f.endswith('.json')]:
    print(f)
    filename=os.path.splitext(f)[0]
    city=filename.split('_')[1]
    time=filename.split('_')[2]
    path_json=os.path.join(results_dir, f)
    print(path_json)
    with open (path_json, 'r', encoding="utf-8") as f:
        result_df=pd.DataFrame(json.load(f))
        result_df['in_paris']=1 if city=="paris" else 0
        result_df['time']=time
    
    results.append(result_df)

face_london_2306.json
../B_images\images\results\face_london_2306.json
face_london_2312.json
../B_images\images\results\face_london_2312.json
face_london_2406.json
../B_images\images\results\face_london_2406.json
face_paris_2306.json
../B_images\images\results\face_paris_2306.json
face_paris_2312.json
../B_images\images\results\face_paris_2312.json
face_paris_2406.json
../B_images\images\results\face_paris_2406.json

In [25]:
results_df=pd.concat(results, axis=0)
print(results_df.shape)
print(results_df[['time','in_paris']].value_counts(dropna=False))

C:\Users\yeliu\AppData\Local\Temp\ipykernel_19472\1086956278.py:1: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results_df=pd.concat(results, axis=0)

(158179, 18)
time  in_paris
2406  1           43074
      0           24885
2312  1           23789
      0           22783
2306  0           21996
      1           21652
Name: count, dtype: int64

In [30]:
results_df.isna().value_counts()

img_path  host_id  has_face  nb_face  face_area_ratio  avg_face_prob  bbox_list  clean_score  lifestyle_score  host_picture_type  age    age_class  gender  smile_score  is_smiling  dominant_emotion  in_paris  time
False     False    False     False    False            False          False      False        False            False              True   True       True    False        False       True              False     False    122217
                                                                                                                                  False  False      False   False        False       False             False     False     35871
                                                                                                                                  True   False      True    False        False       True              False     False        91
Name: count, dtype: int64

In [28]:
## merge avec listing_tactic
path_csv=r"../data_processed\listings_tactics-paris_london-2306_2312_2406.csv"
df=pd.read_csv(path_csv)
print(df.shape)

C:\Users\yeliu\AppData\Local\Temp\ipykernel_19472\3086760193.py:3: DtypeWarning: Columns (6,68,115) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv(path_csv)

(266852, 122)

In [43]:
df.columns.to_list()

['id',
 'listing_url',
 'scrape_id',
 'last_scraped',
 'source',
 'name',
 'description',
 'neighborhood_overview',
 'picture_url',
 'host_id',
 'host_url',
 'host_name',
 'host_since',
 'host_location',
 'host_about',
 'host_response_time',
 'host_response_rate',
 'host_acceptance_rate',
 'host_is_superhost',
 'host_thumbnail_url',
 'host_picture_url',
 'host_neighbourhood',
 'host_listings_count',
 'host_total_listings_count',
 'host_verifications',
 'host_has_profile_pic',
 'host_identity_verified',
 'neighbourhood',
 'neighbourhood_cleansed',
 'neighbourhood_group_cleansed',
 'latitude',
 'longitude',
 'property_type',
 'room_type',
 'accommodates',
 'bathrooms',
 'bathrooms_text',
 'bedrooms',
 'beds',
 'amenities',
 'price',
 'minimum_nights',
 'maximum_nights',
 'minimum_minimum_nights',
 'maximum_minimum_nights',
 'minimum_maximum_nights',
 'maximum_maximum_nights',
 'minimum_nights_avg_ntm',
 'maximum_nights_avg_ntm',
 'calendar_updated',
 'has_availability',
 'availability_30',
 'availability_60',
 'availability_90',
 'availability_365',
 'calendar_last_scraped',
 'number_of_reviews_till_Q',
 'number_of_reviews_ltm',
 'number_of_reviews_l30d',
 'first_review',
 'last_review',
 'review_scores_rating',
 'review_scores_accuracy',
 'review_scores_cleanliness',
 'review_scores_checkin',
 'review_scores_communication',
 'review_scores_location',
 'review_scores_value',
 'license',
 'instant_bookable',
 'calculated_host_listings_count',
 'calculated_host_listings_count_entire_homes',
 'calculated_host_listings_count_private_rooms',
 'calculated_host_listings_count_shared_rooms',
 'reviews_per_month',
 'number_of_reviews_till_nextQ',
 'number_of_reviews_nextQ',
 'booking_rate_l90d',
 'is_within_1km',
 'has_rating',
 'years_since_host',
 'has_since',
 'lang',
 'text_length',
 'has_response_rate',
 'professional_host',
 'open to different cultures',
 'cosmopolitan',
 'international view',
 'cultural exchange',
 'personal life',
 'life experiences',
 'divers interests',
 'hobbies',
 'enjoy life',
 'meet new people',
 'welcoming',
 'friendly',
 'sociable',
 'interpersonal interaction',
 'thoughtful service',
 'attentive to needs',
 'willing to help',
 'responsive',
 'fan of Airbnb',
 'Airbnb community',
 'love Airbnb',
 'travel with Airbnb',
 'group',
 'time',
 'post',
 'in_paris',
 'has_text',
 'lang_fr',
 'lang_en',
 'langue',
 'ouverture',
 'authenticité',
 'sociabilité',
 'auto_promotion',
 'exemplarité',
 'trend']

In [31]:
results_to_merge=results_df[['host_id',"in_paris",'time',"has_face","nb_face","host_picture_type"]]
display(results_to_merge.head())

     host_id  in_paris  time  has_face  nb_face host_picture_type
0   11535647         0  2306         1        1        life_style
1    9409420         0  2306         1        1        life_style
2  222363410         0  2306         1        1         pro_style
3   79823074         0  2306         1        1         pro_style
4  400346818         0  2306         1        1         pro_style

In [34]:
print(df[['time','in_paris']].value_counts(dropna=False))
df['time']=df['time'].astype(str)

time  in_paris
2406  1           62738
      0           49856
2312  0           43172
2306  0           42356
2312  1           35829
2306  1           32901
Name: count, dtype: int64

In [44]:
df_bio_vis=df.merge(results_to_merge, on=['host_id','in_paris',"time"], how='left')

In [46]:
df_bio_vis.head()
print(df_bio_vis.shape)
df_bio_vis.columns.to_list()

(266852, 125)

['id',
 'listing_url',
 'scrape_id',
 'last_scraped',
 'source',
 'name',
 'description',
 'neighborhood_overview',
 'picture_url',
 'host_id',
 'host_url',
 'host_name',
 'host_since',
 'host_location',
 'host_about',
 'host_response_time',
 'host_response_rate',
 'host_acceptance_rate',
 'host_is_superhost',
 'host_thumbnail_url',
 'host_picture_url',
 'host_neighbourhood',
 'host_listings_count',
 'host_total_listings_count',
 'host_verifications',
 'host_has_profile_pic',
 'host_identity_verified',
 'neighbourhood',
 'neighbourhood_cleansed',
 'neighbourhood_group_cleansed',
 'latitude',
 'longitude',
 'property_type',
 'room_type',
 'accommodates',
 'bathrooms',
 'bathrooms_text',
 'bedrooms',
 'beds',
 'amenities',
 'price',
 'minimum_nights',
 'maximum_nights',
 'minimum_minimum_nights',
 'maximum_minimum_nights',
 'minimum_maximum_nights',
 'maximum_maximum_nights',
 'minimum_nights_avg_ntm',
 'maximum_nights_avg_ntm',
 'calendar_updated',
 'has_availability',
 'availability_30',
 'availability_60',
 'availability_90',
 'availability_365',
 'calendar_last_scraped',
 'number_of_reviews_till_Q',
 'number_of_reviews_ltm',
 'number_of_reviews_l30d',
 'first_review',
 'last_review',
 'review_scores_rating',
 'review_scores_accuracy',
 'review_scores_cleanliness',
 'review_scores_checkin',
 'review_scores_communication',
 'review_scores_location',
 'review_scores_value',
 'license',
 'instant_bookable',
 'calculated_host_listings_count',
 'calculated_host_listings_count_entire_homes',
 'calculated_host_listings_count_private_rooms',
 'calculated_host_listings_count_shared_rooms',
 'reviews_per_month',
 'number_of_reviews_till_nextQ',
 'number_of_reviews_nextQ',
 'booking_rate_l90d',
 'is_within_1km',
 'has_rating',
 'years_since_host',
 'has_since',
 'lang',
 'text_length',
 'has_response_rate',
 'professional_host',
 'open to different cultures',
 'cosmopolitan',
 'international view',
 'cultural exchange',
 'personal life',
 'life experiences',
 'divers interests',
 'hobbies',
 'enjoy life',
 'meet new people',
 'welcoming',
 'friendly',
 'sociable',
 'interpersonal interaction',
 'thoughtful service',
 'attentive to needs',
 'willing to help',
 'responsive',
 'fan of Airbnb',
 'Airbnb community',
 'love Airbnb',
 'travel with Airbnb',
 'group',
 'time',
 'post',
 'in_paris',
 'has_text',
 'lang_fr',
 'lang_en',
 'langue',
 'ouverture',
 'authenticité',
 'sociabilité',
 'auto_promotion',
 'exemplarité',
 'trend',
 'has_face',
 'nb_face',
 'host_picture_type']

In [48]:
df_bio_vis[["in_paris",'time',"has_face","nb_face","host_picture_type"]].value_counts(dropna=False)

in_paris  time  has_face  nb_face  host_picture_type
1         2406  1.0       1.0      pro_style            24236
                0.0       0.0      no_person            16989
0         2406  1.0       1.0      pro_style            16328
                0.0       0.0      no_person            15871
          2312  1.0       1.0      pro_style            14308
                                                        ...
1         2306  1.0       10.0     life_style               1
                          11.0     life_style               1
          2406  1.0       10.0     life_style               1
                          11.0     life_style               1
                          13.0     life_style               1
Name: count, Length: 75, dtype: int64

In [49]:
df_bio_vis.to_csv(r"../data_processed\listings_tactics_bio_vis-paris_london-2306_2312_2406.csv", index=False)

## listings_zsc_paris_2312

In [3]:
path_results=r"../data_processed_paris2312\bge_zsc_en.csv"
results=pd.read_csv(path_results)
print(results.shape)
display(results.head())

(7879, 24)

,id,host_about,attentive to needs,welcoming,friendly,sociable,responsive,thoughtful service,international view,interpersonal interaction,...,enjoy life,cultural exchange,divers interests,open to different cultures,travel with Airbnb,fan of Airbnb,love Airbnb,meet new people,personal life,hobbies
0,5396.0,We have spent a lot of time traveling for work...,0.995195,0.986460,0.982835,0.982809,0.973056,0.970217,0.957682,0.953720,...,0.721678,0.588577,0.508959,0.326977,0.312311,0.285508,0.137775,0.111350,0.010742,0.008257
1,81106.0,Independent photographer. \nCyclist. Often on ...,0.811337,0.806805,0.141630,0.584475,0.639749,0.706699,0.766916,0.751882,...,0.712022,0.001054,0.950056,0.270624,0.258570,0.095681,0.021362,0.011969,0.831021,0.879059
2,7397.0,"I am a writer,54, author of novels, books of l...",0.103298,0.073750,0.029494,0.013494,0.380097,0.147684,0.025538,0.002643,...,0.001584,0.012215,0.862305,0.190189,0.001214,0.000321,0.000308,0.000565,0.015806,0.063168
3,7964.0,Hello ! \r\nOur apartment is great and I am su...,0.816022,0.996871,0.993857,0.951562,0.535471,0.842520,0.305249,0.996420,...,0.178647,0.040200,0.174614,0.395662,0.692560,0.294100,0.050386,0.825821,0.251737,0.000458
4,81615.0,We are web startup entrepreneurs and bnb/garde...,0.369725,0.607601,0.237928,0.689847,0.456869,0.445728,0.800902,0.276564,...,0.910597,0.027181,0.943947,0.510266,0.185741,0.541624,0.281515,0.026181,0.606292,0.045909

In [4]:
path_results=r"../data_processed_paris2312\bge_zsc_fr.csv"
results_fr=pd.read_csv(path_results)
print(results_fr.shape)
display(results_fr.head())

(12109, 24)

,id,host_about,accueillant,amical,loisirs,voyager par Airbnb,attentif aux besoins,aime Airbnb,communauté Airbnb,rendre service,...,vie personnelle,parcours personnel,échange culturel,aimer la vie,ouvert aux différentes cultures,adepte d'Airbnb,vue internationale,cosmopolite,passions,rencontrer de nouvelles personnes
0,9952,"Parisienne retraitée, dynamique et accueillant...",0.992812,0.935814,0.909193,0.875256,0.874508,0.856798,0.826970,0.748013,...,0.548789,0.462885,0.284487,0.205789,0.186578,0.152814,0.041465,0.041297,0.035062,0.031609
1,87481,Je trouve un réel plaisir à accueillir mes hôt...,0.998978,0.949157,0.913987,0.499078,0.965520,0.923180,0.980773,0.969415,...,0.969323,0.983606,0.916447,0.530114,0.372059,0.591269,0.021710,0.597080,0.790833,0.527021
2,12452,"Bonjour, nous sommes Get a Key, agence de loca...",0.913307,0.550650,0.077468,0.010862,0.282200,0.019521,0.011468,0.910525,...,0.005395,0.078732,0.001284,0.001317,0.076181,0.051317,0.307512,0.017085,0.000511,0.100833
3,98322,"Je suis française, je vis à Paris , j'ai un fi...",0.755381,0.830792,0.948153,0.002565,0.278240,0.001182,0.001899,0.013593,...,0.918429,0.848644,0.067461,0.856351,0.077722,0.000733,0.049612,0.604864,0.815321,0.412180
4,105210,"Voyage , tranquillité, gastronomie. Respectueu...",0.944876,0.866210,0.969927,0.996801,0.989188,0.978680,0.926851,0.533535,...,0.273843,0.955368,0.166674,0.654079,0.732407,0.998286,0.787293,0.410936,0.714757,0.047297

In [5]:
results_all=pd.concat([results, results_fr], axis=0)
print(results_all.shape)

(19988, 45)

In [6]:
results_all.to_csv(r"../data_processed\paris_2312\resultsZSC_paris_2312.csv", index=False)