In [12]:
import os, sys
import pandas as pd
import json

## results zsc : 2306, 2312, 2406

In [51]:
DATA_DIR="../data_processed"
groups=[   
    'london_2306', "london_2312",'london_2406',
    'paris_2306',"paris_2312","paris_2406"
]
list_df=[]
for g in groups:
    path_df=os.path.join(DATA_DIR, g, f"listings_zsc_{g}.csv")
    print(f"{g}".center(100,'-'))
    print(path_df,os.path.exists(path_df))
    
    df=pd.read_csv(path_df)
    print(df.shape)
    time=g.split("_")[1]
    in_paris="1" if g.split('_')[0]=="paris" else 0
    df["group"]=g
    df['time']=str(time)
    df['post'] = df["time"].apply(lambda x : 1 if x=="2406" else 0)
    df['in_paris']=in_paris

    # check
    if "len" in df:
        df.rename(columns={'len':"text_length"},inplace=True)

    # double check
    df['has_text']=df['lang'].apply(lambda x : 0 if x=="no_text" else 1)
    df['lang_fr']=df['lang'].apply(lambda x : 1 if x=="fr" else 0)
    df['lang_en']=df['lang'].apply(lambda x : 1 if x=="en" else 0)       
        
    list_df.append(df)
df_zsc_all=pd.concat(list_df, axis=0)
print(df_zsc_all.shape)

--------------------------------------------london_2306---------------------------------------------
../data_processed\london_2306\listings_zsc_london_2306.csv True
(42356, 108)
--------------------------------------------london_2312---------------------------------------------
../data_processed\london_2312\listings_zsc_london_2312.csv True
(43172, 112)
--------------------------------------------london_2406---------------------------------------------
../data_processed\london_2406\listings_zsc_london_2406.csv True
(49856, 108)
---------------------------------------------paris_2306---------------------------------------------
../data_processed\paris_2306\listings_zsc_paris_2306.csv True

C:\Users\yeliu\AppData\Local\Temp\ipykernel_31040\2318842080.py:12: DtypeWarning: Columns (59,60) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv(path_df)

(32901, 108)
---------------------------------------------paris_2312---------------------------------------------
../data_processed\paris_2312\listings_zsc_paris_2312.csv True
(35829, 114)
---------------------------------------------paris_2406---------------------------------------------
../data_processed\paris_2406\listings_zsc_paris_2406.csv True
(62738, 107)
(266852, 116)

In [52]:
df_zsc_all.columns.to_list()

['id',
 'listing_url',
 'scrape_id',
 'last_scraped',
 'source',
 'name',
 'description',
 'neighborhood_overview',
 'picture_url',
 'host_id',
 'host_url',
 'host_name',
 'host_since',
 'host_location',
 'host_about',
 'host_response_time',
 'host_response_rate',
 'host_acceptance_rate',
 'host_is_superhost',
 'host_thumbnail_url',
 'host_picture_url',
 'host_neighbourhood',
 'host_listings_count',
 'host_total_listings_count',
 'host_verifications',
 'host_has_profile_pic',
 'host_identity_verified',
 'neighbourhood',
 'neighbourhood_cleansed',
 'neighbourhood_group_cleansed',
 'latitude',
 'longitude',
 'property_type',
 'room_type',
 'accommodates',
 'bathrooms',
 'bathrooms_text',
 'bedrooms',
 'beds',
 'amenities',
 'price',
 'minimum_nights',
 'maximum_nights',
 'minimum_minimum_nights',
 'maximum_minimum_nights',
 'minimum_maximum_nights',
 'maximum_maximum_nights',
 'minimum_nights_avg_ntm',
 'maximum_nights_avg_ntm',
 'calendar_updated',
 'has_availability',
 'availability_30',
 'availability_60',
 'availability_90',
 'availability_365',
 'calendar_last_scraped',
 'number_of_reviews_till_Q',
 'number_of_reviews_ltm',
 'number_of_reviews_l30d',
 'first_review',
 'last_review',
 'review_scores_rating',
 'review_scores_accuracy',
 'review_scores_cleanliness',
 'review_scores_checkin',
 'review_scores_communication',
 'review_scores_location',
 'review_scores_value',
 'license',
 'instant_bookable',
 'calculated_host_listings_count',
 'calculated_host_listings_count_entire_homes',
 'calculated_host_listings_count_private_rooms',
 'calculated_host_listings_count_shared_rooms',
 'reviews_per_month',
 'number_of_reviews_till_nextQ',
 'number_of_reviews_nextQ',
 'booking_rate_l90d',
 'is_within_1km',
 'has_rating',
 'years_since_host',
 'has_since',
 'lang',
 'text_length',
 'has_response_rate',
 'professional_host',
 'open to different cultures',
 'cosmopolitan',
 'international view',
 'cultural exchange',
 'personal life',
 'life experiences',
 'divers interests',
 'hobbies',
 'enjoy life',
 'meet new people',
 'welcoming',
 'friendly',
 'sociable',
 'interpersonal interaction',
 'thoughtful service',
 'attentive to needs',
 'willing to help',
 'responsive',
 'fan of Airbnb',
 'Airbnb community',
 'love Airbnb',
 'travel with Airbnb',
 'group',
 'time',
 'post',
 'in_paris',
 'has_text',
 'lang_fr',
 'lang_en',
 'langue']

In [55]:
df_zsc_all[['time','in_paris']].value_counts()

time  in_paris
2406  1           62738
      0           49856
2312  0           43172
2306  0           42356
2312  1           35829
2306  1           32901
Name: count, dtype: int64

# results pic: 2306, 2312, 2406

In [53]:
results_pic_all=[]
results_pic_folder=r"../B_images\images\results"

for i, f in enumerate([f for f in os.listdir(results_pic_folder) if f.endswith('.json')]):
    city=os.path.splitext(f)[0].split('_')[1]
    time=os.path.splitext(f)[0].split('_')[2]    
    path=os.path.join(results_pic_folder, f)
    # print(i, city,time, path)

    with open(path, "r", encoding="utf-8") as f:
        res = json.load(f)
        print(f'len results on {city} {time}: ',len(res))
        res_df=pd.DataFrame(res)
        res_df['time']=str(time)
        res_df['in_paris']=1 if city=='paris' else 0

        # display(res_df.head())
        results_pic_all.append(res_df)
    # break
df_pic_all=pd.concat(results_pic_all, axis=0)
print(df_pic_all.shape)

len results on london 2306:  21996
len results on london 2312:  22783
len results on london 2406:  24885
len results on paris 2306:  21652
len results on paris 2312:  23789
len results on paris 2406:  43074
(158179, 18)

C:\Users\yeliu\AppData\Local\Temp\ipykernel_31040\1468299879.py:20: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_pic_all=pd.concat(results_pic_all, axis=0)

In [ ]:
df_pic_all.head()

,img_path,host_id,has_face,nb_face,face_area_ratio,avg_face_prob,bbox_list,clean_score,lifestyle_score,host_picture_type,age,age_class,gender,smile_score,is_smiling,dominant_emotion,time,in_paris
0,/content/drive/MyDrive/airbnbMM2/host_pic/imag...,11535647,1,1,0.093077,0.999895,"[[68, 80, 130, 156]]",0.138635,0.146024,life_style,NaN,None,None,0.0,0,None,2306,0
1,/content/drive/MyDrive/airbnbMM2/host_pic/imag...,9409420,1,1,0.012602,0.999273,"[[107, 38, 129, 67]]",0.023957,0.232032,life_style,NaN,None,None,0.0,0,None,2306,0
2,/content/drive/MyDrive/airbnbMM2/host_pic/imag...,222363410,1,1,0.265086,0.973485,"[[53, 0, 163, 122]]",0.327281,0.004539,pro_style,NaN,None,None,0.0,0,None,2306,0
3,/content/drive/MyDrive/airbnbMM2/host_pic/imag...,79823074,1,1,0.009383,0.999997,"[[99, 59, 118, 84]]",0.262700,0.052975,pro_style,NaN,None,None,0.0,0,None,2306,0
4,/content/drive/MyDrive/airbnbMM2/host_pic/imag...,400346818,1,1,0.124820,0.999759,"[[85, 0, 156, 89]]",0.252867,0.060350,pro_style,NaN,None,None,0.0,0,None,2306,0

In [59]:
df_pic_all_clean=df_pic_all[['host_id','time','in_paris','has_face','nb_face',"face_area_ratio","clean_score","lifestyle_score",'host_picture_type']]
df_pic_all_clean.head()
df_pic_all_clean.to_csv(r'../B_images\images\results\results_pic_face-3periods.csv', index=False)

## zsc+pic

In [88]:
print(df_zsc_all['host_id'].dtype)
print(df_pic_all['host_id'].dtype)
print(df_zsc_all['time'].dtype)
print(df_pic_all['time'].dtype)
print(df_zsc_all['in_paris'].dtype)
print(df_pic_all['in_paris'].dtype)

df_zsc_all['host_id']=df_zsc_all['host_id'].astype(int)
df_zsc_all['time']=df_zsc_all['time'].astype(str)
df_zsc_all['in_paris']=df_zsc_all['in_paris'].astype(int)

int64
int64
object
object
int64
int64

In [90]:
df_all=df_zsc_all.merge(df_pic_all_clean, on=['host_id', "time",'in_paris'], how="left")
print(df_all.shape)

(266852, 122)

In [91]:
df_all.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,has_text,lang_fr,lang_en,langue,has_face,nb_face,face_area_ratio,clean_score,lifestyle_score,host_picture_type
0,157714.0,https://www.airbnb.com/rooms/157714,2.023061e+13,2023-06-09,city scrape,Townhouse in Hammersmith · ★4.71 · 1 bedroom ·...,"Large, light and spacious loft bedroom with a ...",The neighbourhood is extremely convenient for ...,https://a0.muscache.com/pictures/4129744/10db5...,757377,...,1,0,1,NaN,1.0,2.0,0.410351,0.000000,0.000000,life_style
1,13913.0,https://www.airbnb.com/rooms/13913,2.023061e+13,2023-06-09,city scrape,Rental unit in Islington · ★4.80 · 1 bedroom ·...,My bright double bedroom with a large window h...,Finsbury Park is a friendly melting pot commun...,https://a0.muscache.com/pictures/miso/Hosting-...,54730,...,1,0,1,NaN,1.0,1.0,0.208514,0.233649,0.074763,pro_style
2,15400.0,https://www.airbnb.com/rooms/15400,2.023061e+13,2023-06-09,city scrape,Rental unit in London · ★4.80 · 1 bedroom · 1 ...,Lots of windows and light. St Luke's Gardens ...,It is Chelsea.,https://a0.muscache.com/pictures/428392/462d26...,60302,...,1,0,1,NaN,1.0,2.0,0.027002,0.000000,0.000000,life_style
3,306333.0,https://www.airbnb.com/rooms/306333,2.023061e+13,2023-06-09,city scrape,Rental unit in London · ★4.32 · 2 bedrooms · 3...,Welcome to my lovely 2-bedroom flat in Hoxton!...,"In Shoreditch, empty walls are future murals. ...",https://a0.muscache.com/pictures/32c818d1-7762...,1573870,...,1,0,1,NaN,1.0,1.0,0.263822,0.329527,0.002855,pro_style
4,159736.0,https://www.airbnb.com/rooms/159736,2.023061e+13,2023-06-09,city scrape,Rental unit in Lambeth · ★4.72 · 1 bedroom · 1...,Calm sunny double room with a queen size bed a...,We love that in Loughborough Junction we live ...,https://a0.muscache.com/pictures/1067303/d2300...,766056,...,1,0,1,NaN,1.0,1.0,0.313600,0.180994,0.114254,pro_style

In [ ]:
print(df_all.host_picture_type.value_counts(dropna=False),'\n')
print(df_all.host_picture_type.value_counts(dropna=False, normalize=True))
# df_all["host_picture_type"]=df_all["host_picture_type"].fillna("no_person")

host_picture_type
pro_style     94648
life_style    80969
no_person     79364
NaN           11871
Name: count, dtype: int64

host_picture_type
pro_style     0.354683
life_style    0.303423
no_person     0.297408
NaN           0.044485
Name: proportion, dtype: float64

In [96]:
path_df_all=r"../data_all\listings_bio_vis-paris_london-2306_2312_2406-1.csv"
df_all.to_csv(path_df_all, index=False)